'use client';

import { jsPDF } from 'jspdf';
import { AssetData } from '../types/global';

interface BlockchainCertificateProps {
  asset: AssetData;
  onDownload: () => void;
}

export function generateBlockchainCertificate(asset: AssetData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Colors
  const primaryColor = '#4F46E5'; // Indigo
  const secondaryColor = '#6B7280'; // Gray
  const accentColor = '#10B981'; // Green
  
  // Header
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('BLOCKCHAIN CERTIFICATE', pageWidth / 2, 25, { align: 'center' });
  
  // Subtitle
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Proof of Creative Asset Registration', pageWidth / 2, 35, { align: 'center' });
  
  // Certificate content
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('CERTIFICATE OF REGISTRATION', pageWidth / 2, 60, { align: 'center' });
  
  // Asset details section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  const startY = 80;
  const lineHeight = 8;
  let currentY = startY;
  
  // Asset Information
  doc.setFont('helvetica', 'bold');
  doc.text('Asset Information:', 20, currentY);
  currentY += lineHeight;
  
  doc.setFont('helvetica', 'normal');
  doc.text(`File Name: ${asset.filename}`, 20, currentY);
  currentY += lineHeight;
  
  doc.text(`File Type: ${asset.mime}`, 20, currentY);
  currentY += lineHeight;
  
  doc.text(`File Size: ${(asset.size / 1024).toFixed(2)} KB`, 20, currentY);
  currentY += lineHeight * 2;
  
  // Blockchain Information
  doc.setFont('helvetica', 'bold');
  doc.text('Blockchain Information:', 20, currentY);
  currentY += lineHeight;
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Network: Sepolia Testnet`, 20, currentY);
  currentY += lineHeight;
  
  doc.text(`Asset ID (SHA256): ${asset.assetId}`, 20, currentY);
  currentY += lineHeight;
  
  doc.text(`Transaction Hash: ${asset.txHash}`, 20, currentY);
  currentY += lineHeight;
  
  // Format registration date
  const registrationDate = new Date(Number(asset.registration.timestamp));
  doc.text(`Registration Date: ${registrationDate.toLocaleDateString()} ${registrationDate.toLocaleTimeString()}`, 20, currentY);
  currentY += lineHeight * 2;
  
  // Verification section
  doc.setFont('helvetica', 'bold');
  doc.text('Verification:', 20, currentY);
  currentY += lineHeight;
  
  doc.setFont('helvetica', 'normal');
  doc.text('This certificate proves that the above file has been registered on the', 20, currentY);
  currentY += lineHeight;
  doc.text('Ethereum Sepolia blockchain with the unique hash shown above.', 20, currentY);
  currentY += lineHeight;
  doc.text('The registration is immutable and can be verified on the blockchain.', 20, currentY);
  currentY += lineHeight * 2;
  
  // Verification URLs
  doc.setFont('helvetica', 'bold');
  doc.text('Verify on Blockchain:', 20, currentY);
  currentY += lineHeight;
  
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(primaryColor);
  doc.text(`Transaction: https://sepolia.etherscan.io/tx/${asset.txHash}`, 20, currentY);
  currentY += lineHeight;
  
  // QR Code placeholder (we'll add a simple text representation)
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('QR Code for Verification:', 20, currentY);
  currentY += lineHeight;
  
  // Simple QR representation (in a real app, you'd use a QR library)
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  const qrSize = 30;
  const qrX = pageWidth - 50;
  const qrY = currentY - 5;
  
  // Draw a simple border for QR code
  doc.rect(qrX, qrY, qrSize, qrSize);
  doc.setFontSize(8);
  doc.text('QR', qrX + qrSize/2 - 2, qrY + qrSize/2 + 1);
  
  // Footer
  const footerY = pageHeight - 30;
  doc.setDrawColor(secondaryColor);
  doc.line(20, footerY, pageWidth - 20, footerY);
  
  doc.setFontSize(10);
  doc.setTextColor(secondaryColor);
  doc.text('Generated by Creative Asset Registry', pageWidth / 2, footerY + 10, { align: 'center' });
  doc.text(`Certificate ID: ${asset.assetId.slice(0, 16)}...`, pageWidth / 2, footerY + 20, { align: 'center' });
  
  // Download the PDF
  const fileName = `blockchain-certificate-${asset.filename.replace(/\.[^/.]+$/, '')}.pdf`;
  doc.save(fileName);
}

export default function BlockchainCertificate({ asset, onDownload }: BlockchainCertificateProps) {
  const handleDownload = () => {
    generateBlockchainCertificate(asset);
    onDownload();
  };

  return (
    <button
      onClick={handleDownload}
      className="inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
    >
      <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Download PDF
    </button>
  );
}
